### ISSUE TITLE
Preview of numbered list is incorrect

### ISSUE THREAD

**Issue by gorohash** [ganta/marktone#262]
If you enter a list with numbers greater than 1, the numbers you enter are previewed as they are.

```
2. foo
3. bar
```

However, when you post it, it appears as a list starting from 1 as shown below.

```
1. foo
2. bar
```

**Comment by ganta** [comment]
@gorohash 
[Marked.js adds a `start` attribute to the `ol` element](https://github.com/markedjs/marked/blob/4b9b71a7568ad148e917bceaa369d807bcfdd43f/src/Renderer.js#L70-L74), so the list starts at the specified number in the preview, but kintone removes the `start` attribute when posting, so the list number is reset.

This cannot be controlled in Marktone.

**Comment by gorohash** [comment]
@ganta Thanks for your response. I understood that Marked.js and kintone are incompatible in their handling of the start attribute.

**Comment by ganta** [comment]
There are some problems because kintone excessively removes HTML elements and attributes.
For example, the details element is not available. Also, #123 is caused by it.
